### ISSUE TITLE
PHP notices when new block instance created and not configured yet

### ISSUE THREAD

**Issue by mudrd8mz** [sekharjaji/moodle-block_socialshare#1]
Notice: Trying to get property of non-object in blocks/socialshare/block_socialshare.php on line 17
Notice: Trying to get property of non-object in blocks/socialshare/block_socialshare.php on line 18
Notice: Trying to get property of non-object in blocks/socialshare/block_socialshare.php on line 19

**Comment by sekharjaji** [comment]
I am not sure how to fix this. I added a check around this.
