### ISSUE TITLE
I am confused by block_socialshare::get_url()

### ISSUE THREAD

**Issue by mudrd8mz** [sekharjaji/moodle-block_socialshare#3]
I am really confused by the `get_url()` method of your block class. As far as I can see, there is not place where `$this->config->urltype` would get set so it always returns an empty string. Am I missing something? What is the point of this method?

**Comment by sekharjaji** [comment]
You are correct. I missed out implementing that part. I will add it asap. Thanks.

**Comment by sekharjaji** [comment]
Fixed
